### ISSUE TITLE
local 관련

### ISSUE THREAD

**Issue by mewo042** [hiun/NanumBarunGothic#5]
현재 css를 보면 레귤러 굵기의 local 부분이 다음과 같이 되어 있습니다.

 src: local('Nanum Barun Gothic Regular'), local('Nanum Barun Gothic-Regular'), local('NanumBarunGothic Regular');

local로 시작하는 부분이 컴퓨터에 설치된 폰트 중에서 다음과 같은 것이 있으면 그것을 쓰고, 없으면 url을 다운받아 폰트를 보여주는 것으로 압니다. 그런데 현재 쓰인 위 3가지 폰트 이름은 어디에서도 존재하지 않는 이름입니다. 레귤러 굵기의 이름은 'NanumBarunGothic' 아니면 '나눔바른고딕'입니다. 

볼드도 마찬가지로 3가지 형태를 모두 쓸 필요 없이 'NanumBarunGothic Bold'와 같이 하나만 지정하면 될 것 같습니다.

횡설수설해서 무슨 말인지 알아들으실까 모르겠네요;

**Comment by hiun** [comment]
답변이 굉장히 늦었습니다. 말씀하신 그 부분 찾아보니 현재 코드가 분명 문제가 있는것은 확실한것 같네요.

http://www.w3.org/TR/css3-fonts/#descdef-src 에 따르면 local의 argument에 설치된 폰트명을 넣는것이 맞다고 보여집니다. 그러나 어떤분들은 local을 생략하고

`font-family: 'NanumBarunGothic Bold'`

처럼 최종 사용되는곳에만 적어도 브라우저가 local을 참조 한다고도 합니다. 조금 헷갈리는데 어떤 의견이신가요?
